### PR TITLE
fix: Update dependencies version (#615)

### LINKED ISSUE #615: Update dependencies
[versions.properties](https://github.com/crowdin/crowdin-cli/blob/main/versions.properties)

only minor and patch versions

### PR DESCRIPTION
**Pull request by ddninja**
Updated minor and patch version of dependencies listed on version.properties

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
@ddninja thank you! The CI build has failed, could you please take a look?

**Comment by ddninja** [comment]
@andrii-bodnar On checking I found out that the pipeline is failing because of upgrading the commons-io library.
on reverting it to 2.11.0 it is passing the pipeline. 
In commons-io version 2.14.0 (updated version) , IOUtils.readLines() throw UncheckedIOException instead of IOException (as in 2.11.0).
I will update the catch statement for catching UncheckedIOException.

**Comment by andrii-bodnar** [comment]
@ddninja updating the catch statement sounds good to me.

**Review by andrii-bodnar — APPROVED** [review]
@ddninja thank you!

**Pull request merged**
