### PR TITLE
test: Add Unit tests for the `PreTranslateAction.java` class

### LINKED ISSUE #659: Add Unit tests for the `PreTranslateAction.java` class
**References:**

- [`PreTranslateAction.java`](https://github.com/crowdin/crowdin-cli/blob/main/src/main/java/com/crowdin/cli/commands/actions/PreTranslateAction.java)
- [`PreTranslateAction.java` coverage](https://app.codecov.io/gh/crowdin/crowdin-cli/blob/main/src%2Fmain%2Fjava%2Fcom%2Fcrowdin%2Fcli%2Fcommands%2Factions%2FPreTranslateAction.java)

This class has no coverage by Unit tests. We need to add more Unit tests to cover it.

### PR DESCRIPTION
**Pull request by Sweetdevil144**
Fixes #659 .
+ @andrii-bodnar . I haven't touched private METHODS for security reasons, so the code coverage will be a bit less, around 30%. If you want me to run tests for them too, then I surely can do It.

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
@Sweetdevil144 could you please specify which private classes you mean? 

I guess it should be possible to cover the other methods in this class by passing different values to the `act` method and mocking all the `client` methods' calls.

**Comment by Sweetdevil144** [comment]
> @Sweetdevil144 could you please specify which private classes you mean?

Oh Sorry. I mistakenly types classes. Updated the comment

**Comment by Sweetdevil144** [comment]
> I guess it should be possible to cover the other methods in this class by passing different values to the `act` method and mocking all the `client` methods' calls.

Sure. let me try that too.

**Comment by andrii-bodnar** [comment]
@Sweetdevil144 it looks like the `GlossaryDownloadActionTest` and `TmDownloadActionTest` are good examples in this case

**Comment by Sweetdevil144** [comment]
Hey @andrii-bodnar . I tried adjusting the files as you recommeded. However I'm getting a lot of NullPointerExceptions at lines like -> 

```java
action.act(out, properties, client);
```

for test cases like 

```java
@Test
    void testPrepareFileIds_SomeSourcesDoNotExistInProjectPaths() {
        Language english = new Language();
        english.setId("en");
        when(project.getProjectLanguages(false)).thenReturn(Collections.singletonList(english));
        when(project.getDirectories()).thenReturn(new HashMap<>());
        when(project.getBranches()).thenReturn(new HashMap<>());
        when(project.getFileInfos()).thenReturn(Collections.emptyList());

        action.act(out, properties, client);

        verify(out, times(1)).println(anyString());
    }
```

**Comment by andrii-bodnar** [comment]
Hey @Sweetdevil144, probably you need to mock the Crowdin client.

Like in this test - [`GlossaryDownloadActionTest.java`](https://github.com/crowdin/crowdin-cli/blob/main/src/test/java/com/crowdin/cli/commands/actions/GlossaryDownloadActionTest.java)

**Comment by Sweetdevil144** [comment]
Sorry @andrii-bodnar . This seems unbelievably 'Out' of my reach  :- |

**Comment by Sweetdevil144** [comment]
This is what it says in each test case
Screenshot 2023-10-16 at 10 41 47 PM
a Runtine Exception

**Comment by Sweetdevil144** [comment]
I'm still encountring RuntimeError Exceptions which is demonstrated by the recent commit

**Comment by andrii-bodnar** [comment]
@Sweetdevil144 it says "Language 'en' doesn't exist in the project". It means that your project mock doesn't return this language.

Probably, you'll need to update this mock:

```java
when(project.getProjectLanguages(false)).thenReturn(Collections.<Language>emptyList());
```

to return a list of languages instead of an empty list.

**Comment by Sweetdevil144** [comment]
Sorry @andrii-bodnar , I cant seem to get a hold of this. I would like to close this PR!
Thanks!!

**Comment by andrii-bodnar** [comment]
@Sweetdevil144 I just looked closer at this and prepared an almost working example based on your code:

```java
package com.crowdin.cli.commands.actions;

import com.crowdin.cli.client.ProjectBuilder;
import com.crowdin.cli.commands.Outputter;
import com.crowdin.cli.client.ProjectClient;
import com.crowdin.cli.properties.NewPropertiesWithFilesUtilBuilder;
import com.crowdin.cli.properties.PropertiesWithFiles;
import com.crowdin.cli.client.CrowdinProjectFull;
import com.crowdin.cli.utils.Utils;
import com.crowdin.client.translations.model.PreTranslationStatus;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import java.util.Collections;

import static org.mockito.Mockito.*;

class PreTranslateActionTest {

    @Mock
    private Outputter out;

    @Mock
    private ProjectClient client;

    @Mock
    private PreTranslationStatus preTranslationStatus;

    private PreTranslateAction action;

    private PropertiesWithFiles pb;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.initMocks(this);

        action = new PreTranslateAction(
            Collections.singletonList("ua"), null, 1L, null, null, false, false, false, false, false, false, false, null
        );

        NewPropertiesWithFilesUtilBuilder pbBuilder = NewPropertiesWithFilesUtilBuilder
            .minimalBuiltPropertiesBean("android.xml", "%two_letters_code%.xml")
            .setBasePath(Utils.PATH_SEPARATOR);
        pb = pbBuilder.build();

        CrowdinProjectFull project = ProjectBuilder.emptyProject(Long.parseLong(pb.getProjectId()))
            .addFile("android.xml", "android", 101L, null, null, "%two_letters_code%.xml")
            .build();

        when(client.downloadFullProject(null)).thenReturn(project);
        when(client.startPreTranslation(any())).thenReturn(preTranslationStatus);
        when(preTranslationStatus.getStatus()).thenReturn("finished");
    }

    @Test
    void testAct_FailureWhenPreTranslationFails() {
        when(preTranslationStatus.getStatus()).thenReturn("processing", "failed");
        when(client.checkPreTranslation(anyString())).thenReturn(preTranslationStatus);

        action.act(out, pb, client);
    }
}
```

Currently, this is failing with the `Couldn't find any files to Pre-Translate in the current project` error since the `prepareFileIds` method returns an empty list. This is happening because the `SourcesUtils.getFiles` tries to find files in the filesystem and I didn't find a way to mock this method. 

Maybe we can create some temporary files locally during the test execution? These files should match the `source` pattern in the `NewPropertiesWithFilesUtilBuilder` configuration.

**Pull request closed without merging**
