### PR TITLE
ci: automate chocolatey publishing

### PR DESCRIPTION
**Pull request by andrii-bodnar**

### CODE REVIEW

**Comment by ye4241** [comment]
Hello @andrii-bodnar , I will post my reply here too, with better markdown format. Please try to contact me here.

1. `update.ps1` is useless for your situation. 
2. Please add `choco push --api-key $env:xxx` logic in the publish.yaml, and make sure you have keep the api-key as secret env.
3. Set some automatic logic as below just like au logic in your [bump-version.yml](https://github.com/crowdin/crowdin-cli/blob/cli3/.github/workflows/bump-version.yml)
  a. update the version property in nuspec file
  b. update the url and checksum for install.ps1

**Comment by andrii-bodnar** [comment]
@ye4241 thanks a lot for the details!

**Comment by andrii-bodnar** [comment]
@ye4241 just updated my PR a bit - added automatic versioning and the publishing step

**Comment by andrii-bodnar** [comment]
I am still not sure about the `packageSourceUrl` configuration

**Comment by ye4241** [comment]
`packageSourceUrl` is right for the chocolatey folder with branch.
I have noticed that you may already done with automatic version and publishing step, it looks pretty very well.
A question about semantic-release (first time for me to use this npm package) , should `chocolatey/crowdin-cli.nuspec` and `chocolatey/tools/chocolateyinstall.ps1` add to `@semantic-release/git`.`assets` due to these files is changed?

**Comment by andrii-bodnar** [comment]
@ye4241 you are right, missed this, thank you!

**Comment by andrii-bodnar** [comment]
Hi @ye4241,

the new version was successfully published automatically via GH Actions yesterday - [crowdin-cli/3.11.0](https://community.chocolatey.org/packages/crowdin-cli/3.11.0) 🎉 

thanks again for the help!

**Comment by ye4241** [comment]
Hi @andrii-bodnar 

Congratulations on the successful deployment, please remove me from maintainers of chocolatey package if needed.

**Pull request merged**
