### PR TITLE
fix: throw error if no translations were found

### LINKED ISSUE #822: Do not return Exit Code Null if all files failed to download via CLI
CLI is a part of GitHub Action in my case, and it may happen that my configuration file (crowdin.yml) is outdated, so nothing will be fetched.

CLI returns Exit Code Null in this case, and GitHub Action is marked as successful:
image

**Preferred solution**
It should return an Exit Code that will help to mark GHA as `Failed`, any non zero exit code works

### PR DESCRIPTION
**Pull request by yevheniyJ**

### CODE REVIEW

**Review by andrii-bodnar — APPROVED** [review]

**Comment by sbrandwoo** [comment]
Please can you consider reverting this change. We run crowdin-sync via the github action and now our jobs are failing with the following:

> ❌ Couldn't find any file to download. Since you are using the 'Skip untranslated files' option, please make sure you have fully translated files

There's no error here, everything is working as expected, but now the process is failing.

**Comment by ben-wharton** [comment]
As @sbrandwoo says, we run this workflow daily on >100 repos in our infra, and this caused many engineers to wonder why their builds appear to be failing (whereas really their translations just aren't ready yet).

**Comment by andrii-bodnar** [comment]
@sbrandwoo @ben-wharton Sorry for the inconvenience. 

If the `skip untranslated files` option is enabled, we can probably still exit with code 0 as before. It looks like that would be pretty expected in this case.

@yevheniyJ, what do you think?

**Comment by yevheniyJ** [comment]
Agree, sorry for inconvenience. PR with fix is prepared https://github.com/crowdin/crowdin-cli/pull/829
CC @andrii-bodnar

**Comment by andrii-bodnar** [comment]
@sbrandwoo @ben-wharton the new versions are already available:

https://github.com/crowdin/crowdin-cli/releases/tag/4.1.1
https://github.com/crowdin/github-action/releases/tag/v2.1.1

**Pull request merged**
