### PR TITLE
fix: correct detection of obsolete files with double asterisk pattern

### LINKED ISSUE #790: `--delete-obsolete` not working correctly when including `/**/` in source pattern
When including `/**/` in the source pattern (`crowdin.yml`) deleted files aren't detected anymore.

### `crowdin.yml` file:
```
"base_path": "."
"preserve_hierarchy": true

"files": [
  {
    "source": "/**/sources/*.strings",
    "translation": "/**/translations/%osx_locale%/%original_file_name%"
  }
]
```
### Project structure:
```
├── crowdin.yml
├── crowdin_credentials.yml
└── someFeature
    └── sources
        ├── file1.strings
        ├── file2.strings
        └── file3.strings
```
(I don't added any translations, since that's not relevant for the issue)

### 1. Upload sources
```
crowdin upload sources \
    --auto-update \
    --delete-obsolete \
    --identity crowdin_credentials.yml
```

### 2. Delete a file
`rm someFeature/sources/file1.strings`

### 3. Upload sources again
```
crowdin upload sources \
    --auto-update \
    --delete-obsolete \
    --identity crowdin_credentials.yml

// output
✔️  Fetching project info     
✔️  File 'someFeature/sources/file3.strings'
✔️  File 'someFeature/sources/file2.strings'
✔️  No obsolete files were found
✔️  No obsolete directories found
```

**In Crowdin:**
Screenshot 2024-05-14 at 09 16 32

**Locally:**
```
├── crowdin.yml
├── crowdin_credentials.yml
└── someFeature
    └── sources
        ├── file2.strings
        └── file3.strings
```

## Expected
The locally deleted `file1.strings` is removed from Crowdin and the CLI output reflects the removal of `file1.strings`.

## Additional information
I couldn't reproduce the issue without the `/**/` pattern. ~~Since #775 also used the `/**/` pattern, I'm wondering whether there is some other difference I haven't seen so far.~~ In https://github.com/anbraten/repro-crowdin-delete-obsolete/blob/main/crowdin.yml#L6 @anbraten doesn't use `/**/` (only in the issue description `/**/` is used).
When using branches, the issue appears only for existing branches. Meaning that if I run
```
crowdin upload sources \
    --auto-update \
    --delete-obsolete \
    --branch someBranch \
    --identity crowdin_credentials.yml

// output
✔️  Fetching project info     
✔️  Branch 'someBranch'
✔️  Directory 'someBranch/someFeature'
✔️  Directory 'someBranch/someFeature/sources'
✔️  File 'someBranch/someFeature/sources/file2.strings'
✔️  File 'someBranch/someFeature/sources/file3.strings'
✔️  No obsolete files were found
✔️  No obsolete directories found
```
after step 3 from above, the `file1.strings` is successfully deleted for `someBranch` from Crowdin. 
Screenshot 2024-05-14 at 09 25 31

However, if I delete another file (`rm someFeature/sources/file2.strings`) and running
```
crowdin upload sources \
    --auto-update \
    --delete-obsolete \
    --branch someBranch \
    --identity crowdin_credentials.yml

// output
✔️  Fetching project info     
⏭  Branch 'someBranch' already exists in the project
✔️  File 'someBranch/someFeature/sources/file3.strings'
✔️  No obsolete files were found
✔️  No obsolete directories found
```
again, `file2.strings` is still present in `someBranch` on Crowdin.

Screenshot 2024-05-14 at 09 27 53

## Environment
 - macOS
 - Crowdin CLI 3.19.3

### PR DESCRIPTION
**Pull request by anbraten**
closes #790

### CODE REVIEW

**Comment by anbraten** [comment]
@andrii-bodnar @finebel This should be it.

**Comment by andrii-bodnar** [comment]
@anbraten thanks a lot for your contribution! 🚀 

The build has failed, could you please take a look?

**Comment by andrii-bodnar** [comment]
@finebel could you please download the build and check whether it fixes the issue for you?

https://github.com/crowdin/crowdin-cli/actions/runs/9093764457 (artifacts)

You can run it as follows:

```console
java -jar crowdin-cli-x.x.x.jar push
```

**Comment by finebel** [comment]
@anbraten Thanks for the fast implementation. With https://github.com/crowdin/crowdin-cli/actions/runs/9093764457 I can't reproduce the issue described in #790 👍. 

However, I encountered the following behaviour. I'm not sure whether it's a bug or intended. It might also be unrelated to the new changes ~~(I haven't tested it with the current release version).~~ 
EDIT: I have tested it with the current 3.19.3 release and the behaviour is the same. So it seems to be unrelated.

### 1. `crowdin.yml`
```
"base_path": "."
"preserve_hierarchy": true

"files": [
  {
    "source": "/**/sources/*.strings",
    "translation": "/**/translations/%osx_locale%/%original_file_name%"
  }
]
```
With the following project structure:
```
├── crowdin.yml
├── crowdin_credentials.yml
└── someFeature
    └── sources
        ├── file1.strings
        ├── file2.strings
        └── file3.strings
```

### 2. Upload
```
java -jar crowdin-cli-3.19.3.jar upload sources \
    --auto-update \
    --delete-obsolete \
    --identity crowdin_credentials.yml
```
Result:
Screenshot 2024-05-15 at 14 54 14

### 3. Change `crowdin.yml`
```
"base_path": "."
"preserve_hierarchy": true

"files": [
  {
    "source": "/**/someDir/**/sources/*.strings",
    "translation": "/**/someDir/**/translations/%osx_locale%/%original_file_name%"
  }
]
```
(added `/**/someDir/` to `source` and `translation` pattern).

Updated local project structure:
```
├── crowdin.yml
├── crowdin_credentials.yml
└── someDir
    └── someFeature
        └── sources
            ├── file1.strings
            ├── file2.strings
            └── file3.strings
```

### 4. Upload again
```
java -jar crowdin-cli-3.19.3.jar upload sources \
    --auto-update \
    --delete-obsolete \
    --identity crowdin_credentials.yml

// output:
✔️  Fetching project info     
✔️  Directory 'someDir'
✔️  Directory 'someDir/someFeature'
✔️  Directory 'someDir/someFeature/sources'
✔️  File 'someDir/someFeature/sources/file3.strings'
✔️  File 'someDir/someFeature/sources/file1.strings'
✔️  File 'someDir/someFeature/sources/file2.strings'
✔️  No obsolete files were found
✔️  No obsolete directories found
```
Result:
Screenshot 2024-05-15 at 14 58 26

@andrii-bodnar What do you think?

**Comment by andrii-bodnar** [comment]
@finebel thanks for confirming that the original issue is now fixed 🚀 

I think the second issue is somehow related to the double `**` in the `source` and `translation` pattern. The current implementation probably doesn't handle such cases well. Honestly, it's quite tricky to handle such complex patterns 🙂

**Comment by anbraten** [comment]
Lemme do some more testing and check if I can fix that issue directly as well.

**Comment by anbraten** [comment]
That issue seems to be coming from a completely different part now. The `exportPattern` is wrong:

- Expected: "/someDir/someFeature/translations/%osx_locale%/%original_file_name%"
- Got: "/someDir/someFeature/someDir/someDir/someFeature/translations/%osx_locale%/%original_file_name%"

I get this `exportPattern` directly after fetching the project from the api client.

**Comment by andrii-bodnar** [comment]
Hmm, so I guess it happens at the moment the source files are uploaded to Crowdin when the CLI gets the patterns, transforms `**` to the actual path and then passes the `exportPattern` in the request. Then that pattern is set as the export pattern for the source file

**Comment by finebel** [comment]
Just as a side note: It's much more important to me that the issue in #790 is fixed now. At the moment, I don't have a use case which would require the second issue to be solved (I encountered it mainly out of curiosity). Of course, it would be nice to see the second issue solved as well - but I guess it would be sufficient to fix it as part of a new PR if it's not trivial.

**Comment by andrii-bodnar** [comment]
Definitely, I am going to release a new version with the fix tomorrow.

**Review by andrii-bodnar — APPROVED** [review]
@anbraten @finebel Thank you guys for your contributions and participation! 🙌

**Comment by andrii-bodnar** [comment]
Available in [3.19.4](https://github.com/crowdin/crowdin-cli/releases/tag/3.19.4)

**Comment by anbraten** [comment]
@andrii-bodnar Thanks. 

Out of curiosity is the cli also used by the official Github integration or would I need to use the github action instead?

**Comment by andrii-bodnar** [comment]
@anbraten the official GitHub Action uses this CLI under the hood. It's already updated as well 🙂 

https://github.com/crowdin/github-action/releases/tag/v1.20.4 (the `v1` tag also contains the latest version)

**Comment by anbraten** [comment]
Awesome. I was aware of the github action using the cli. I not sure regarding this app as it seems to have / had similar issues with deleting obsolete files: https://crowdin.com/store/apps/github

**Comment by andrii-bodnar** [comment]
This is the native GitHub integration, it doesn't use the CLI. As far as I know, it can also delete obsolete files, and in fact, I'm not aware of any recent complaints about this feature in the native app

**Pull request merged**
