### PR TITLE
Fixed a problem writing to a configuration file

### PR DESCRIPTION
**Pull request by rx2000**

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
@rx2000 please rebase your branch, there are a conflicts

**Comment by rx2000** [comment]
done

**Comment by rx2000** [comment]
@andrii-bodnar done

**Comment by andrii-bodnar** [comment]
@rx2000 the branch was not rebased, still conflicts

**Comment by rx2000** [comment]
@andrii-bodnar done 2.0)

**Pull request closed without merging**
