### PR TITLE
test: Add Unit tests for the `ListLanguagesAction.java` class

### LINKED ISSUE #658: Add Unit tests for the `ListLanguagesAction.java` class
**References:**

- [`ListLanguagesAction.java`](https://github.com/crowdin/crowdin-cli/blob/main/src/main/java/com/crowdin/cli/commands/actions/ListLanguagesAction.java)
- [`ListLanguagesAction.java` coverage](https://app.codecov.io/gh/crowdin/crowdin-cli/blob/main/src%2Fmain%2Fjava%2Fcom%2Fcrowdin%2Fcli%2Fcommands%2Factions%2FListLanguagesAction.java)

This class has no coverage by Unit tests. We need to add more Unit tests to cover it.

### PR DESCRIPTION
**Pull request by Sweetdevil144**
Fix #658 .
+ Added Unit tests for file `ListLanguagesAction.java`
+ Current code coverage = 65% for the file.
+ Code coverage can be further improved by contributors further on this month.

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
@Sweetdevil144 thank you!

Could you please also include tests to cover the **56-58** and **70-83** lines?

https://app.codecov.io/gh/crowdin/crowdin-cli/pull/663/blob/src/main/java/com/crowdin/cli/commands/actions/ListLanguagesAction.java

Screenshot 2023-10-12 at 09 20 30

**Comment by Sweetdevil144** [comment]
Okay sure. Doing it now!!

**Comment by Sweetdevil144** [comment]
@andrii-bodnar Increased the code coverage

**Review by andrii-bodnar — APPROVED** [review]
@Sweetdevil144 thank you!

**Pull request merged**
