### PR TITLE
fix: Error when the user puts options before the subcommand

### PR DESCRIPTION
**Pull request by mrexodia**
These will be silently ignored due to a bug in picocli (#833)

Does this need localization for the error message itself?

### CODE REVIEW

**Review by andrii-bodnar — COMMENTED** [review]
Thanks for your contribution!

A few comments:

- There could be options starting with `-`, it should also be handled correctly.
- move the text to the resource bundle (`resources/messages/messages.properties`).

**Comment by andrii-bodnar** [comment]
Honestly, it looks more like a hack. @yevheniyJ maybe you'll have some other ideas?

**Comment by mrexodia** [comment]
Addressed your review points. I of course agree it's a hack, but this error really would have saved me a lot of debugging frustrations 😅

**Comment by yevheniyJ** [comment]
First of all this fix won't help if option was passed in the middle of the command, e.g. `cli.jar string --verbose list`. Fix only considers first argument.

Second point: there is just no way to detect whether or not order is correct, especially where we have root commands with subcommands and multiple arguments with their values (or array of values).

The proper fix would be I guess to use inherit scopes for options https://picocli.info/#_inherited_options and bypass them from root to target subcommands. But this require extra research.

**Comment by mrexodia** [comment]
I tried the inherited options, but this explodes in picocli because multiple classes inherit from `GenericCommand` and that creates duplicate options:

```
picocli.CommandLine$DuplicateOptionAnnotationsException: Option name '--no-progress' is used by both field boolean com.crowdin.cli.commands.picocli.GenericCommand.noProgress and field boolean com.crowdin.cli.commands.picocli.GenericCommand.noProgress
	at picocli.CommandLine$DuplicateOptionAnnotationsException.create(CommandLine.java:18698)
	at picocli.CommandLine$DuplicateOptionAnnotationsException.access$2900(CommandLine.java:18692)
	at picocli.CommandLine$Model$CommandSpec.addOption(CommandLine.java:6786)
	at picocli.CommandLine$Model$CommandSpec.add(CommandLine.java:6770)
	at picocli.CommandLine$Model$CommandSpec.addSubcommand(CommandLine.java:6601)
	at picocli.CommandLine$Model$CommandReflection.initSubcommands(CommandLine.java:11885)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11850)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:6392)
	at picocli.CommandLine.<init>(CommandLine.java:230)
	at picocli.CommandLine.toCommandLine(CommandLine.java:3635)
	at picocli.CommandLine.access$16700(CommandLine.java:148)
	at picocli.CommandLine$Model$CommandReflection.initSubcommands(CommandLine.java:11884)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11850)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:6392)
	at picocli.CommandLine.<init>(CommandLine.java:230)
	at picocli.CommandLine.<init>(CommandLine.java:224)
	at picocli.CommandLine.<init>(CommandLine.java:199)
	at com.crowdin.cli.commands.picocli.PicocliRunner.init(PicocliRunner.java:57)
	at com.crowdin.cli.commands.picocli.PicocliRunner.<init>(PicocliRunner.java:21)
	at com.crowdin.cli.commands.picocli.PicocliRunner.getInstance(PicocliRunner.java:26)
	at com.crowdin.cli.Cli.main(Cli.java:15)
```

That being said, I don't think it's very likely the a user will pass `--no-color` between sub commands. I'm used to other command line tools where the root options mentioned in `--help` will work before the first sub command, which is why I did it wrong.

**Comment by yevheniyJ** [comment]
It seems like if we allow to pass option in another position, then picocli won’t allow any other position. At least this is my impression. And there is no obvious fix. I think for now we won’t do anything since it’s anyway not the correct usage of our CLI and in documentation we multiple times showing how, with what commands, options, in which order, tool should be used.

**Pull request closed without merging**
