### PR TITLE
crowdin-cli: Update subdependencies and code for Gradle 7.1

### LINKED ISSUE #372: Vulnerabilities in dependencies
**Is your feature request related to a problem? Please describe.**
When we scanning our project by Aquasec (tools for scanning docker images on vulnerabilities) we get 2 critical vulnerabilities from crowdin-cli:
- jackson-databind
- log4j-core

**Describe the solution you'd like**
Upgrade package log4j-core to version 2.8.2 or above. Upgrade package jackson-databind to version 2.9.10.3 or above.

### PR DESCRIPTION
**Pull request by Myself5**
Gradle 6.5.1 is not working with Java 16 (and I couldn't get it working with Java 8 on ArchLinux either).

Changes:
* Update maven URL to use HTTPS (Gradle 7 requirement).
* Update Gradle and wrapper to the latest Version (7.1.1).
* Update build.gradle to replace deprecated "enabled" flag with "required".
* Update all subdependencies to latest as some required updates for the Gradle update.
* Adjust code to match changes between zip4j 1.3.2 and 2.8.0.

Tests: Build, Pass tests, run a quick translation pull.

### CODE REVIEW

**Comment by Myself5** [comment]
-1, still having some runtime issues. will solve ASAP

**Comment by Myself5** [comment]
Further updated shadow, spotbugs, jacoco and checkstyle as those were incompatible with Java 16 as well.  Working fine on my ArchLinux setup now.

**Comment by andrii-bodnar** [comment]
@Myself5 thanks a lot for your contribution!

**Comment by andrii-bodnar** [comment]
@frombetelgeuse please review this PR.

**Review by frombetelgeuse — APPROVED** [review]

**Comment by andrii-bodnar** [comment]
@Myself5 will it be compatible with previous Gradle and java versions?

**Comment by Myself5** [comment]
> Compatible with previous Gradle

Should be irrelevant, as the included gradle wrapper (which is 7.1) is what downloads Gradle and manages the rest. The "host" version of Gradle should therefore be irrelevant. (e.g. I don't even have gradle installed.)

> Older Java Versions:

I've tested it with Java 16 and 8, Compiled it on 16, ran fine on 16 as well as 8, compiled it on 8, ran fine on 16 and 8 as well.

Both on a x86_64 system.

If there's any other edgecases that might need to be covered, let me know and I'll try.

**Comment by andrii-bodnar** [comment]
@Myself5 merged this PR and discovered that the static analysis [job was failed](https://dev.azure.com/crowdin/crowdin-cli-3/_build/results?buildId=7311&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=f8ed7bd8-2a7f-56f6-9385-7fc29a8b5b7b). 

is there any way to fix this?

**Comment by Myself5** [comment]
Terribly sorry, I could swear that passed when I tested it. I'll take a look immediately.

**Comment by Myself5** [comment]
Ok, found it. The Upgrade to Checkstyle 8.44 appears to require some config updates, it's working fine with 8.34. Will check on which changes are required and open another PR.

**Comment by Myself5** [comment]
Fixed in #373

**Pull request merged**
